import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

Future<Autogenerated> weekWeather() async {
  //api 호출을 위한 주소
  //http request의 결과 즉 api 호출의 결과를 받기 위한 변수

  String jsonString = await rootBundle.loadString('images/weekData.json');

  final jsonResponse = json.decode(jsonString); //받은 정보를 json형태로 decode
  //받은 데이터정보를 필요한 형태로 저장한다.
  //weekWeather =

  return new Autogenerated.fromJson(jsonResponse);
}

class Autogenerated {
  List<Week>? week;

  Autogenerated({this.week});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['week'] != null) {
      week = <Week>[];
      json['week'].forEach((v) {
        week!.add(new Week.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.week != null) {
      data['week'] = this.week!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Week {
  String? main;
  int? tempMax;
  int? tempMin;
  String? rain;
  int? day;

  Week({this.main, this.tempMax, this.tempMin, this.rain, this.day});

  Week.fromJson(Map<String, dynamic> json) {
    main = json['main'];
    tempMax = json['temp_max'];
    tempMin = json['temp_min'];
    rain = json['rain'];
    day = json['day'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['main'] = this.main;
    data['temp_max'] = this.tempMax;
    data['temp_min'] = this.tempMin;
    data['rain'] = this.rain;
    data['day'] = this.day;
    return data;
  }
}
